### ISSUE TITLE
inconsistent time zones

### ISSUE THREAD

**Issue by dragosmiron** [infused/ziptz#1]
Hi,
What is the source of these time zones?
For example any zipcode in Hawaii shows up as an alaskan timezone instead of Honolulu timezone.

**Comment by infused** [comment]
It looks like I introduced this bug when remapping the time zones to use standard TZ database names. I inadvertently set Hawaii zip codes to "America/Adak" instead of "Pacific/Honolulu". 

I've fixed this in version 2.0.4, so give that version a try.
