### ISSUE TITLE
Incorrect time zone for 85144.

### ISSUE THREAD

**Issue by mr-notorious** [infused/ziptz#12]
Hi Keith,

I was randomly eye bawling the dataset and noticed zip 85144 is mapped to America/Los_Angeles, where as all the surrounding zips are mapped to America/Phoenix. 

After some quick Googling, I see that zip 85144 was introduce last year to replace 85142 (America/Phoenix). https://about.usps.com/newsroom/local-releases/az/2023/0530-usps-adds-new-zip-code-in-rapidly-growing-queen-creek-area.htm

Thanks for the great project!

**Comment by infused** [comment]
Thank you for pointing this out. Much appreciated! It has been corrected, and the fix is included in gem version 5.1.2.
