### ISSUE TITLE
Missing Zip Codes

### ISSUE THREAD

**Issue by sfdcbahu** [infused/ziptz#2]
Hi, Thanks a lot for this great service. I noticed that there are some missing zip codes. So i just wanted to point that out as it might help others as well. here are some : 

45427 81134 81153 85219 85220 85222 85223 85228  85231 85232 85239 85241 85242 85243 85247 85272 85273 94013

**Comment by infused** [comment]
None of these zip codes are valid. Many of them were replaced nearly 10 years ago.  You can try to look them up here:

https://tools.usps.com/zip-code-lookup.htm?citybyzipcode
