### ISSUE TITLE
Data file source

### ISSUE THREAD

**Issue by k3davis** [infused/ziptz#5]
Thanks for this helpful project, and for keeping it updated.

Can you disclose how you generate or source your data files?

**Comment by tomaszhanc** [comment]
@infused awesome job! Could reveal a secret how did you manage to gather those data?

**Comment by infused** [comment]
The process continues to evolve. It started out with open source zip code data and then moved to commercial data sources. I'm unsatisfied with the accuracy of these sources, so I'm now finalizing a propriety process using the USPS data directly combined with a custom geocode database I've developed. This gem will start using data from the new process early next year.

**Comment by k3davis** [comment]
@infused I personally would welcome you to make that process available, not just from within ziptz but perhaps as a standalone project. I was asking the question because I need reliable (or even mostly reliable) data of this sort outside of ruby, so going to the source is helpful.

I have access to a commercial data source, but have also found it to be highly inaccurate...

**Comment by infused** [comment]
You're in luck - I just started selling the data based on the new process via the AWS Data Marketplace:

https://aws.amazon.com/marketplace/pp/prodview-4vcapflqwntdw?qid=1576789503970&sr=0-2
